[package]
name = "cat-or-dog-nnet"
version = "0.1.0"
authors = ["Shing Lyu <shing.lyu@gmail.com>"]
edition = "2018"

[dependencies]
rusty-machine = "0.5.4"
csv = "1.1"
rand = "0.7.0"
rand_distr = "0.2.1"
gnuplot = "0.0.31"
structopt = "0.3.1"
serde = { version = "1.0.100", features = ["derive"] }
